databases:
  - name: mace
    databaseName: mace
    user: mace

services:
  - type: web
    name: mace
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mace
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
