databases:
  - name: mace
    databaseName: mace
    user: mace

services:
  - type: web
    name: mace
    env: ruby
    plan: free
    buildCommand: bundle install
    startCommand: bundle exec ruby app.rb
    # envVars:
    #   - key: DATABASE_URL
    #     fromDatabase:
    #       name: mace
    #       property: connectionString
    #   - key: RAILS_MASTER_KEY
    #     sync: false
